### ISSUE TITLE
add "valid" output to encoders

### ISSUE THREAD

**Issue by bgelb-openai** [xlsynth/bedrock-rtl#101]
It would be helpful to have the onehot2bin converter have a valid output that indicates that one of the inputs was "hot" vs. all inputs zero.

One-hot but w/ all bits zero when nothing is valid is turning out to be a pretty common occurance.

@mgottscho if it sounds good I will go ahead and send a PR.

FYI @btowles-openai

**Comment by mgottscho** [comment]
SGTM

**Comment by mgottscho** [comment]
@bgelb-openai are you still planning to do a PR?

**Comment by mgottscho** [comment]
Unassigning from @zhemao-openai, we have a new hire who will help do this as first PR :D
