### ISSUE TITLE
add "one-hot mux"

### ISSUE THREAD

**Issue by bgelb-openai** [xlsynth/bedrock-rtl#102]
A common pattern I am seeing is that the (one-hot) grant output from an arbiter wants to control a mux that selects the winner.

In such a case, I have tended to do something like:

grant -> onehot2bin -> mux (i.e. an assign statement that uses the bin value as a select)

Seems to me a pattern like the following would be a bit more natural:

```
always_comb
  data_out = '0
    for(int i=0;i<NumInputs;i++) begin
       data_out |= {DataWidth{grant[i]}} & data_in[i];
    end
end
```

@mgottscho do you think itd make sense to add a component w/ this pattern (that is intended to be paired directly w/ an arb's grant output)?

FYI @btowles-openai

**Comment by mgottscho** [comment]
SGTM. Suggest to call this `br_mux_onehot`. We should also do a `br_mux_bin` for the binary-encoded select variant.
