### ISSUE TITLE
FIFO support for memory with non-zero read latency

### ISSUE THREAD

**Issue by zhemao-openai** [xlsynth/bedrock-rtl#112]
The current br_fifo_ctrl_1r1w implementation requires the read latency to be zero, which basically restricts us to flop-based storage. For SRAM-based storage, we'll need to extend the FIFO to support non-zero latencies. This will require either a staging FIFO or reorder buffer (depending on setting of EnableBypass=1) to absorb the read latency.

**Comment by mgottscho** [comment]
Yep. It'll be a substantial chunk of work to have it support all the planned variations (push/pop ready/credit combinations). We can start with ready/valid and push-credit/valid where the variants already exist

**Comment by zhemao-openai** [comment]
Fixed by #140
