### ISSUE TITLE
Expose corrected ECC bits from br_ecc_secded_decoder

### ISSUE THREAD

**Issue by zhemao-openai** [xlsynth/bedrock-rtl#234]
The SECDED decoder module performs correction on the entire codeword for single bit flip. However, only the data portion is exported and not the corrected ECC bits. It would be helpful to have them output as well.

**Comment by mgottscho** [comment]
Starting this now

**Comment by mgottscho** [comment]
Fixed in https://github.com/xlsynth/bedrock-rtl/pull/252
