### ISSUE TITLE
Add reinit and reinit_value ports to the br_counter_* variants.

### ISSUE THREAD

**Issue by rahulnagarajan-openai** [xlsynth/bedrock-rtl#68]
Currently we are using rst to init the values to MAX or MIN values. I would like the following changes

- Add a reinit port to allow us to reinitialize the values to MAX or MIN value post reset
- Add a reinit_val (which user can tie to MAX/MIN or a user specified value) to reinitialize the counter to when reinit is set.

**Comment by mgottscho** [comment]
Will do this today.
