### ISSUE TITLE
FIFOs may be buggy when EnableBypass = 1

### ISSUE THREAD

**Issue by mgottscho** [xlsynth/bedrock-rtl#83]
Unit tests don't work when EnableBypass is 1. Most likely DUT bugs, need to investigate

**Comment by zhemao-openai** [comment]
The bypass implementation will change when we add support for non-zero read latency. I'll look into it then.

**Comment by zhemao-openai** [comment]
This should be fixed by the recent FIFO changes. At least the unit tests with EnableBypass=1 are passing.
